INSERT INTO Jogador VALUES(1,1);
INSERT INTO Jogador VALUES(2,1);
INSERT INTO Jogador VALUES(3,1);
INSERT INTO Jogador VALUES(4,1);
INSERT INTO Jogador VALUES(5,1);

INSERT INTO Clube VALUES(1);

INSERT INTO Epoca VALUES(1);

INSERT INTO Equipa VALUES(1,1,1);